### ISSUE TITLE
template filename

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/rdls-spreadsheet-template#12]
Template names should reference RDLS?
full.xlsx, etc, are not hugely helpful when in a file storage system outside of this repo.

suggest 'rdls_' added as prefix to all templates

**Comment by duncandewhurst** [comment]
Good spot. I'll update once https://github.com/GFDRR/rdls-spreadsheet-template/issues/14 is resolved since it includes some suggestions for filenames.

**Comment by duncandewhurst** [comment]
Done in https://github.com/GFDRR/rdls-spreadsheet-template/commit/d7a41f6a698d63ec0e612fa4161fa13c71c9020d
