### ISSUE TITLE
Colors for spreadsheet tabs

### ISSUE THREAD

**Issue by matamadio** [GFDRR/rdls-spreadsheet-template#15]
Please use visual identity colors for spreadsheet tabs:

![immagine](https://github.com/GFDRR/rdls-spreadsheet-template/assets/44863827/7f15f0d8-8daf-43d9-80e2-848b0825f968)

![immagine](https://github.com/GFDRR/rdls-spreadsheet-template/assets/44863827/432dab29-db6c-4758-abbc-175584c0dd53)

**Comment by duncandewhurst** [comment]
Done in a7c311355ac80f859e07f9fc0163667fedd3b8fd
