### ISSUE TITLE
Content for documentation

### ISSUE THREAD

**Issue by duncandewhurst** [GFDRR/rdls-spreadsheet-template#2]
https://github.com/GFDRR/rdls-spreadsheet-template/issues/1 contains a couple of suggestions for things to include in the documentation for the spreadsheet template:

> > Looks good. I don't think it's worth to strip out any tab; if some are not used, could those be removed by the user?
> 
> Yes, users can remove sheets. We can include instructions to that effect in the documentation.

> > * What does the '0' refer to in the field names?
> 
> It indicates that each row under that field path should be interpreted as an item in an array, e.g. under `attributions/0/id` the first row will be interpreted as the `id` of the first item in the `attributions` array and the second row will be interpreted as the `id` of the second item, etc. We can explain this in the documentation.

We can use this issue to log any other content to include in the documentation.

**Comment by odscjen** [comment]
explain how to enter `author_names` in spreadsheet - @duncandewhurst do you think this is best placed in the documentation or within the spreadsheet description cell?

**Comment by duncandewhurst** [comment]
I prefer to keep the description fields aligned with the schema so we can explain how to enter array fields in the documentation since the same instructions will apply to other fields, e.g. `Location.bbox`.

**Comment by odscjen** [comment]
sounds good, and is my preference too

**Comment by duncandewhurst** [comment]
I've updated the readme with the content from this issue, plus a how-to guide and developer documentation.
