### ISSUE TITLE
dataset id path should be identifier as per the schema

### ISSUE THREAD

**Issue by odscjen** [GFDRR/rdls-spreadsheet-template#7]
Currently in the spreadsheet on sheet `datasets` cell B1 is `id` but it should be `identifier`

**Comment by duncandewhurst** [comment]
I've changed `identifier` to `id` in the schema in https://github.com/GFDRR/rdl-standard/pull/181 because Flatten Tool requires identifiers to have consistent field names and we've used `id` everywhere but the top-level object. Therefore, there's no change required to the spreadsheet template.
