### ISSUE TITLE
Auto-populate and hide the links sheet

### ISSUE THREAD

**Issue by duncandewhurst** [GFDRR/rdls-spreadsheet-template#8]
Per @matamadio's suggestion in https://github.com/GFDRR/rdl-standard/issues/187#issuecomment-1674418662, we can auto-populate and hide the links sheet so that users don't mistakenly add data to it.

**Comment by duncandewhurst** [comment]
This is done in https://github.com/GFDRR/rdls-spreadsheet-template/commit/234857f4f2969d5f3ea2ab731be8412588a450a1 and tested in Google Sheets. However, there seems to be an issue with how LibreOffice handles the formulae, which leads to the input cells in the `links` sheet being populated with `0` rather than being empty.

@matamadio please could you open the [latest version of the template](https://github.com/GFDRR/rdls-spreadsheet-template/raw/main/templates/full.xlsx) in Excel and check that rows 8 onwards are blank. Thanks!

**Comment by matamadio** [comment]
![immagine](https://github.com/GFDRR/rdls-spreadsheet-template/assets/44863827/a58cf374-99f0-43c7-9a76-8ccbdd3d1260)
Sorry, they are not :(

**Comment by duncandewhurst** [comment]
Fixed in https://github.com/GFDRR/rdls-spreadsheet-template/commit/0ea9141222f0ab20d420e075d53c5638e3a53d52 and working OK now in LibreOffice so I assume it works in Excel, too. Please reopen if not!
